language: csharp
sudo: required
dist: trusty
mono: latest
dotnet: 2.0.0
os:
  - linux
cache:
  directories:
    - tools
before_cache:
  - rm -f tools/packages.config
script:
  - git fetch --unshallow
  - git fetch origin master:refs/remotes/origin/master
  - git branch -r
  - chmod 755 ./build.sh
  - ./build.sh --verbosity Diagnostic
