trigger:
  batch: true
  branches:
    include:
      - master
  tags:
    include:
      - "*"
pr:
  branches:
    include:
      - master

resources:
  repositories:
    - repository: rsg
      type: github
      name: RocketSurgeonsGuild/AzureDevopsTemplates
      ref: refs/tags/v0.3.0
      endpoint: github

variables:
  Configuration: Release
  Verbosity: Normal
  DotNetVersion: "2.2.101"
  CakeVersion: "0.31.0"
  NuGetVersion: "4.9.2"
  Coverage: "$(Agent.BuildDirectory)/c"
  VstsCoverage: "$(Coverage)"
  Artifacts: $(Build.ArtifactStagingDirectory)
  VstsArtifacts: "$(Artifacts)"
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: "true"

jobs:
  - job: GitVersion
    pool:
      vmImage: "VS2017-Win2016"
    steps:
      - template: gitversion/store.yml@rsg
        parameters:
          NuGetVersion: $(NuGetVersion)

  - template: pipeline/cake-job.yml@rsg
    parameters:
      name: "macOS"
      dependsOn: GitVersion
      vmImage: "macOS-10.13"
      pushNuget: false
      Configuration: $(Configuration)
      Verbosity: $(Verbosity)
      CakeVersion: $(CakeVersion)
      DotNetVersion: $(DotNetVersion)
      NuGetVersion: $(NuGetVersion)

  - template: pipeline/cake-job.yml@rsg
    parameters:
      name: "Linux"
      dependsOn: GitVersion
      vmImage: "Ubuntu-16.04"
      pushNuget: false
      Configuration: $(Configuration)
      Verbosity: $(Verbosity)
      CakeVersion: $(CakeVersion)
      DotNetVersion: $(DotNetVersion)
      NuGetVersion: $(NuGetVersion)

  - job: Windows
    dependsOn: GitVersion
    pool:
      vmImage: "VS2017-Win2016"
    steps:
      - template: gitversion/restore.yml@rsg
      - template: cake/install.yml@rsg
        parameters:
          CakeVersion: $(CakeVersion)
          DotNetVersion: $(DotNetVersion)
      # Nuget is required for test scripts below
      - task: NuGetToolInstaller@0
        displayName: "Get NuGet"
        inputs:
          versionSpec: $(NuGetVersion)
      - template: cake/run.yml@rsg
        parameters:
          Configuration: $(Configuration)
          Verbosity: $(Verbosity)
      - template: publish-artifacts.yml@rsg
        parameters:
          Configuration: $(Configuration)
      - template: standard/nuget-push.yml@rsg
        parameters:
          NuGetVersion: $(NuGetVersion)
