resources:
  repositories:
    - repository: rsg
      type: github
      name: RocketSurgeonsGuild/AzureDevopsTemplates
      ref: refs/heads/master
      endpoint: github

variables:
  Configuration: Release
  Verbosity: Normal
  DotNetVersion: "2.1.403"
  CakeVersion: "0.30.0"
  NuGetVersion: '4.7.1'
  Coverage: "$(Agent.BuildDirectory)/c"
  VstsCoverage: "$(Coverage)"
  Artifacts: $(Build.ArtifactStagingDirectory)
  VstsArtifacts: "$(Artifacts)"
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: "true"

jobs:
  - job: GitVersion
    pool:
      vmImage: "VS2017-Win2016"
    steps:
      - template: gitversion/store.yml@rsg
        parameters:
          NuGetVersion: $(NuGetVersion)

  - template: pipeline/cake-job.yml@rsg
      parameters:
        name: 'macOS'
        dependsOn: GitVersion
        vmImage: "macOS-10.13"
        pushNuget: false
        Configuration: ${{ parameters.Configuration }}
        Verbosity: ${{ parameters.Verbosity }}
        CakeVersion: ${{ parameters.CakeVersion }}
        DotNetVersion: ${{ parameters.DotNetVersion }}
        NuGetVersion: ${{ parameters.NuGetVersion }}

  - template: pipeline/cake-job.yml@rsg
      parameters:
        name: 'Linux'
        dependsOn: GitVersion
        vmImage: "Ubuntu-16.04"
        pushNuget: false
        Configuration: ${{ parameters.Configuration }}
        Verbosity: ${{ parameters.Verbosity }}
        CakeVersion: ${{ parameters.CakeVersion }}
        DotNetVersion: ${{ parameters.DotNetVersion }}
        NuGetVersion: ${{ parameters.NuGetVersion }}

  - job: Windows
    dependsOn: GitVersion
    pool:
      vmImage: "VS2017-Win2016"
    steps:
      - template: gitversion/restore.yml@rsg
      - template: cake/install.yml@rsg
        parameters:
          CakeVersion: $(CakeVersion)
          DotNetVersion: $(DotNetVersion)
      # Nuget is required for test scripts below
      - task: NuGetToolInstaller@0
        displayName: "Get NuGet"
        inputs:
          versionSpec: $(NuGetVersion)
      - template: cake/run.yml@rsg
        parameters:
          Configuration: $(Configuration)
          Verbosity: $(Verbosity)
      - template: standard/nuget-push.yml@rsg
        parameters:
          NuGetVersion: $(NuGetVersion)
