variables:
  Configuration: Release
  Verbosity: Normal
  Coverage: "$(Agent.BuildDirectory)/c"
  VstsCoverage: "$(Coverage)"
  Artifacts: $(Build.ArtifactStagingDirectory)
  VstsArtifacts: "$(Artifacts)"
  # system.enableAccessToken: 'true'
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: "true"
  DotNetVersion: "2.1.401"
  NuGetVersion: "4.6.2"
  CakeVersion: "0.30.0"
resources:
  containers:
    - container: sdk
      image: microsoft/dotnet:2.1-sdk
jobs:
  - job: GitVersion
    pool:
      vmImage: "VS2017-Win2016"
    steps:
      - template: .pipelines/gitversion-store.yml

  - job: macOS
    dependsOn: GitVersion
    pool:
      vmImage: "macOS-10.13"
    steps:
      - template: .pipelines/gitversion-restore.yml
      - task: DotNetCoreInstaller@0
        displayName: Install dotnet $(DotNetVersion)
        inputs:
          packageType: 'sdk'
          version: ${{ parameters.DotNetVersion }}
      - template: .pipelines/dotnet-core.yml
        parameters:
          CakeVersion: "$(CakeVersion)"
          DotNetVersion: "$(DotNetVersion)"
      - task: RocketSurgeonsGuild.variable-tools.ShowVariables.ShowVariables@1
        displayName: 'Show Variables'
      - template: .pipelines/azure-build.yml
        parameters:
          Configuration: "$(Configuration)"
          Verbosity: "$(Verbosity)"

  - job: Linux
    dependsOn: GitVersion
    container: sdk
    pool:
      vmImage: "Ubuntu-16.04"
    steps:
      - template: .pipelines/gitversion-restore.yml
      - template: .pipelines/dotnet-core.yml
        parameters:
          CakeVersion: "$(CakeVersion)"
          DotNetVersion: "$(DotNetVersion)"
      - task: RocketSurgeonsGuild.variable-tools.ShowVariables.ShowVariables@1
        displayName: 'Show Variables'
      - template: .pipelines/azure-build.yml
        parameters:
          Configuration: "$(Configuration)"
          Verbosity: "$(Verbosity)"

  - job: Windows
    dependsOn: GitVersion
    container: sdk
    pool:
      vmImage: "VS2017-Win2016"
    steps:
      - template: .pipelines/gitversion-restore.yml
      - template: .pipelines/dotnet-core.yml
        parameters:
          CakeVersion: "$(CakeVersion)"
          DotNetVersion: "$(DotNetVersion)"
      - task: NuGetToolInstaller@0
        displayName: "Get NuGet"
        inputs:
          versionSpec: 4.7.1
      - task: RocketSurgeonsGuild.variable-tools.ShowVariables.ShowVariables@1
        displayName: 'Show Variables'
      - template: .pipelines/azure-build.yml
        parameters:
          Configuration: "$(Configuration)"
          Verbosity: "$(Verbosity)"
