trigger:
  branches:
    include:
      - master
      - refs/tags/*
pr:
  autoCancel: true
  branches:
    include:
      - master

resources:
  repositories:
    - repository: rsg
      type: github
      name: RocketSurgeonsGuild/AzureDevopsTemplates
      ref: refs/tags/v0.7.12
      endpoint: github

variables:
  - group: rsg-bot
  - name: CONFIGURATION
    value: Release
  - name: VERBOSITY
    value: Normal
  - name: COVERAGE
    value: "$(Agent.BuildDirectory)/c"
  - name: ARTIFACTS
    value: $(Build.ArtifactStagingDirectory)
  - name: DOTNET_SKIP_FIRST_TIME_EXPERIENCE
    value: "true"
  - name: CodeCovToken
    value: 'e79b91ca-8b9d-4490-b679-a7583193a6d0'

jobs:
  - job: GitVersion
    pool:
      vmImage: "VS2017-Win2016"
    steps:
      - template: gitversion/store.yml@rsg
        parameters:
          NuGetVersion: "5.1.0"

  - template: pipeline/cake-job.yml@rsg
    parameters:
      name: "macOS"
      dependsOn: GitVersion
      vmImage: "macOS-10.14"
      pushNuget: false
      Configuration: $(Configuration)
      Verbosity: $(Verbosity)
      DotNetVersion: "2.2.300"
      DotNet3Version: "3.0.100-preview6-012264"
      NuGetVersion: "5.1.0"

  - template: pipeline/cake-job.yml@rsg
    parameters:
      name: "Linux"
      dependsOn: GitVersion
      vmImage: "Ubuntu-16.04"
      pushNuget: false
      Configuration: $(Configuration)
      Verbosity: $(Verbosity)
      DotNetVersion: "2.2.300"
      DotNet3Version: "3.0.100-preview6-012264"
      NuGetVersion: "5.1.0"

  - job: Windows
    dependsOn: GitVersion
    pool:
      vmImage: "windows-2019"
    steps:
      - template: gitversion/restore.yml@rsg
      - template: cake/install.yml@rsg
        parameters:
          DotNetVersion: "2.2.300"
          DotNet3Version: "3.0.100-preview6-012264"
          NuGetVersion: "5.1.0"
      # Nuget is required for test scripts below
      - task: NuGetToolInstaller@1
        displayName: "Get NuGet"
        inputs:
          versionSpec: "5.1.0"
      - template: cake/run.yml@rsg
        parameters:
          Configuration: $(Configuration)
          Verbosity: $(Verbosity)
      - template: publish-artifacts.yml@rsg
        parameters:
          Configuration: $(Configuration)

  - ${{ if ne(variables['System.PullRequest.IsFork'], 'true') }}:
    - job: GitHub_Draft_Release
      pool:
        vmImage: "windows-2019"
      dependsOn:
        - GitVersion
      steps:
        # - checkout: none
        - template: ../gitversion/restore.yml
        - ${{ if eq(parameters.GitHub, 'true') }}:
          - template: standard/github-draft-release.yml@rsg
            parameters:
              DotNetVersion: ${{ parameters.DotNetVersion }}
              DotNet3Version: ${{ parameters.DotNet3Version }}

    - job: Publish
      pool:
        vmImage: "windows-2019"
      dependsOn:
        - macOS
        - Linux
        - Windows
        - GitHub_Draft_Release
      steps:
        - task: DownloadBuildArtifacts@0
          displayName: "Download NuGet Packages"
          inputs:
            specificBuildWithTriggering: true
            downloadType: single
            artifactName: 'Nupkg - Windows'
            downloadPath: $(Build.ArtifactStagingDirectory)/nuget/
        - template: standard/nuget-push.yml@rsg
          parameters:
            NuGetVersion: "5.1.0"
            GitHubPackages: false

    - job: GitHub_Release
      pool:
        vmImage: "windows-2019"
      dependsOn:
        - macOS
        - Linux
        - Windows
        - GitHub_Draft_Release
      steps:
        - template: gitversion/restore.yml@rsg
        - template: standard/github-release.yml@rsg
          parameters:
            DotNetVersion: "2.2.300"
            DotNet3Version: "3.0.100-preview6-012264"

